print("\n\n\n\n\n\n\n\n")
print("#####################################")
print("#                                   #")
print("#        Hola, mundo!               #")
print("#                                   #")
print("#####################################\n\n\n\n\n\n\n\n")
