print("\n\n\n\n\n\n\n\n")
print("#################################################")
print("#                                               #")
print("#        Hola, mundo! Soy Tanjiro  :3           #")
print("#                                               #")
print("#################################################\n\n\n\n\n\n\n\n")
